# Generated by Django 5.2.8 on 2026-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganatizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('logo_path', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'db_table': 'organization_profile',
            },
        ),
    ]
