# Generated by Django 5.2.8 on 2026-02-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('address_of_institution', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('estimated_income', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'collateral_affiliations',
            },
        ),
        migrations.CreateModel(
            name='CollateralBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_saving', models.CharField(max_length=50)),
                ('child_saving', models.CharField(max_length=50)),
                ('total_saving', models.CharField(max_length=50)),
                ('share_amount', models.CharField(max_length=50)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'collateral_basic',
            },
        ),
        migrations.CreateModel(
            name='CollateralFamilyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('relation', models.CharField(max_length=100)),
                ('member_of_other_coop', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('monthly_income', models.CharField(max_length=50)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'collateral_family_details',
            },
        ),
        migrations.CreateModel(
            name='CollateralIncomeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'collateral_income_expense',
            },
        ),
        migrations.CreateModel(
            name='CollateralProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('father_or_spouse_name', models.CharField(max_length=200)),
                ('grandfather_or_father_inlaw_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('municipality_vdc', models.CharField(max_length=100)),
                ('sheet_no', models.CharField(max_length=50)),
                ('ward_no', models.CharField(max_length=10)),
                ('plot_no', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('land_type', models.CharField(max_length=100)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'collateral_properties',
            },
        ),
    ]
