# Generated by Django 5.2.8 on 2026-02-08 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('generated_date', models.DateField()),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'report_tracking',
                'ordering': ['-generated_date'],
            },
        ),
    ]
