# Generated by Django 5.2.8 on 2026-02-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=100, unique=True)),
                ('interest_rate', models.FloatField()),
            ],
            options={
                'db_table': 'loan_schemes',
            },
        ),
        migrations.CreateModel(
            name='ApprovalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.CharField(max_length=50)),
                ('entered_by', models.CharField(max_length=200)),
                ('entered_post', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=200)),
                ('approver_post', models.CharField(max_length=100)),
                ('remarks', models.TextField(max_length=50)),
                ('approved_loan_amount', models.CharField(max_length=50)),
                ('approved_loan_amount_words', models.TextField()),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'approval_info',
            },
        ),
        migrations.CreateModel(
            name='GuarantorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_member_number', models.CharField(blank=True, max_length=50, null=True)),
                ('guarantor_name', models.CharField(max_length=200)),
                ('guarantor_address', models.CharField(max_length=300)),
                ('guarantor_ward', models.CharField(max_length=10)),
                ('guarantor_phone', models.CharField(max_length=20)),
                ('guarantor_citizenship', models.CharField(max_length=50)),
                ('guarantor_grandfather', models.CharField(max_length=200)),
                ('guarantor_father', models.CharField(max_length=200)),
                ('guarantor_citizenship_issue_district', models.CharField(max_length=100)),
                ('guarantor_age', models.CharField(max_length=10)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'guarantor_details',
            },
        ),
        migrations.CreateModel(
            name='LoanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField()),
                ('loan_duration', models.CharField(max_length=50)),
                ('repayment_duration', models.CharField(max_length=50)),
                ('loan_amount', models.CharField(max_length=50)),
                ('loan_amount_in_words', models.TextField()),
                ('loan_completion_year', models.CharField(max_length=10)),
                ('loan_completion_month', models.CharField(max_length=10)),
                ('loan_completion_day', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'loan_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManjurinamaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('grandfather_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('wada_no', models.CharField(max_length=10)),
                ('tole', models.CharField(max_length=100)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'manjurinama_details',
            },
        ),
        migrations.CreateModel(
            name='WitnessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('tole', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'witness_info',
            },
        ),
    ]
