# Generated by Django 5.2.8 on 2026-03-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanscheme_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalinfo',
            old_name='approver_post',
            new_name='approved_post',
        ),
    ]
