# Generated by Django 5.2.8 on 2026-02-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('self_investment', models.CharField(max_length=50)),
                ('request_loan_amount', models.CharField(max_length=50)),
                ('total_budget_for_project', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(db_column='member_number', on_delete=django.db.models.deletion.CASCADE, to='members.member', to_field='member_number')),
            ],
            options={
                'db_table': 'project_detail',
            },
        ),
    ]
