# Generated by Django 5.2.8 on 2026-03-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetail',
            old_name='request_loan_amount',
            new_name='requested_loan_amount',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='total_budget_for_project',
            new_name='total_cost',
        ),
    ]
