# Generated by Django 5.2.8 on 2026-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('member_number', models.CharField(max_length=50, unique=True)),
                ('member_name', models.CharField(max_length=200)),
                ('member_name_nepali', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dob_bs', models.CharField(blank=True, max_length=20, null=True)),
                ('citizenship_no', models.CharField(blank=True, max_length=50, null=True)),
                ('national_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('grandfather_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('ward_no', models.CharField(blank=True, max_length=10, null=True)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_address', models.CharField(blank=True, max_length=300, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('job_address', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'member_info',
                'ordering': ['-date'],
            },
        ),
    ]
